### ISSUE TITLE
bwm-ng and par2cmdline missing

### ISSUE THREAD

**Issue by iarp** [UnRAIDES/unRAID-NerdTools#29]
Just updated from 6.9 to 6.11 and I removed and reinstalled NerdTools. 

bwm-ng and par2cmdline are missing

**Comment by Mcklaren** [comment]
Hi,

both packages are not there because nerdtools is not nerdpack and not all the packages that were in nerdpack are there. If you want any package you make a request and we will evaluate if it can be added. For now only official packages or packages that are in slackbuild.org are added. 

If you need something open a new ticket and request it.

Best regards.

**Comment by iarp** [comment]
Wouldn't this be a request?

**Comment by Mcklaren** [comment]
The bmw-ng package is spelled correctly because I can't find it. Could you confirm if this is the name of the package ?

**Comment by iarp** [comment]
https://github.com/vgropp/bwm-ng

**Comment by Mcklaren** [comment]
OK, 
We will try to add it in the next update.

Best regards.

**Comment by Mcklaren** [comment]
Hi,

Fixed on version 2024.01.07

Best regards.
